name: Deploy Etf Predictor API to Raspberry Pi 5

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
      # 1. Clonează repository-ul
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Instalează pip și dependențele Python
      - name: Install pip and Python dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      # 3. Construiește imaginea Docker
      - name: Build Docker image
        run: |
          docker build -t etf-predictor-api:latest .

      # 4. Salvează și transferă imaginea pe Raspberry Pi
      - name: Save and transfer image to Raspberry Pi
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          docker save etf-predictor-api:latest -o etf-predictor-api.tar
          scp -i ~/.ssh/id_rsa -P 15621 etf-predictor-api.tar antonio@antonio-dev.go.ro:/home/antonio/

      # 5. Încarcă imaginea și pornește containerul pe Raspberry Pi
      - name: Load image and deploy on Raspberry Pi
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -i ~/.ssh/id_rsa -p 15621 antonio@antonio-dev.go.ro "
             docker load -i /home/antonio/etf-predictor-api.tar &&
             docker stop etf-predictor-api || true &&
             docker rm etf-predictor-api || true &&
             docker run -d --name etf-predictor-api -p 8080:8000 etf-predictor-api:latest
          "

      # 6. Curăță fișierele temporare de pe Raspberry Pi
      - name: Clean up Docker images and tar files on Raspberry Pi
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -i ~/.ssh/id_rsa -p 15621 antonio@antonio-dev.go.ro "
             rm /home/antonio/etf-predictor-api.tar
          "